package model.service;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import model.service.common.AppModule;

import model.view.PocStylesVOImpl;
import model.view.WpStyleSetupVOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 01 11:19:25 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }
    
    
    public void setSessionValues(String orgId, String userId, String respId,
                                 String respApplId) {  
        
        System.out.println("====================  set session values    ================================");
        
        
       orgId = "343";
       userId = "5219";
    //
    //       System.out.println(" orgId "+ orgId  + "  data type  "+ orgId.getClass().getName());
    //
       
        FacesContext fctx = FacesContext.getCurrentInstance();
        ExternalContext ectx = fctx.getExternalContext();
        HttpSession userSession = (HttpSession)ectx.getSession(false);

        if (orgId != null) {
            userSession.setAttribute("orgId", orgId);
        }

        if (userId != null) {
            userSession.setAttribute("userId", userId);
        }

        if (respId != null) {
            userSession.setAttribute("respId", respId);
        }

        if (respApplId != null) {
            userSession.setAttribute("respApplId", respApplId);
        }         
         
      }
    
    
    
    

    /**
     * Container's getter for WpStyleSetupVO1.
     * @return WpStyleSetupVO1
     */
    public ViewObjectImpl getWpStyleSetupVO1() {
        return (ViewObjectImpl)findViewObject("WpStyleSetupVO1");
    }

    /**
     * Container's getter for WpStyleWiseProcessSamVO1.
     * @return WpStyleWiseProcessSamVO1
     */
    public ViewObjectImpl getWpStyleWiseProcessSamVO1() {
        return (ViewObjectImpl)findViewObject("WpStyleWiseProcessSamVO1");
    }

    /**
     * Container's getter for WpStyleWiseProcessSamR01Link1.
     * @return WpStyleWiseProcessSamR01Link1
     */
    public ViewLinkImpl getWpStyleWiseProcessSamR01Link1() {
        return (ViewLinkImpl)findViewLink("WpStyleWiseProcessSamR01Link1");
    }


    /**
     * Container's getter for OrgVO1.
     * @return OrgVO1
     */
    public ViewObjectImpl getOrgVO1() {
        return (ViewObjectImpl)findViewObject("OrgVO1");
    }

    /**
     * Container's getter for SamVO1.
     * @return SamVO1
     */
    public ViewObjectImpl getSamVO1() {
        return (ViewObjectImpl)findViewObject("SamVO1");
    }

    /**
     * Container's getter for OrgVO_vs_SamVO_VL1.
     * @return OrgVO_vs_SamVO_VL1
     */
    public ViewLinkImpl getOrgVO_vs_SamVO_VL1() {
        return (ViewLinkImpl)findViewLink("OrgVO_vs_SamVO_VL1");
    }

    /**
     * Container's getter for PocStylesVO1.
     * @return PocStylesVO1
     */
    public PocStylesVOImpl getPocStylesVO1() {
        return (PocStylesVOImpl)findViewObject("PocStylesVO1");
    }
}
