package model.entity;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 01 10:58:32 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WpStyleSetupEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        StyleSetupId {
            public Object get(WpStyleSetupEOImpl obj) {
                return obj.getStyleSetupId();
            }

            public void put(WpStyleSetupEOImpl obj, Object value) {
                obj.setStyleSetupId((Number)value);
            }
        }
        ,
        SystemId {
            public Object get(WpStyleSetupEOImpl obj) {
                return obj.getSystemId();
            }

            public void put(WpStyleSetupEOImpl obj, Object value) {
                obj.setSystemId((Number)value);
            }
        }
        ,
        OrderQty {
            public Object get(WpStyleSetupEOImpl obj) {
                return obj.getOrderQty();
            }

            public void put(WpStyleSetupEOImpl obj, Object value) {
                obj.setOrderQty((Number)value);
            }
        }
        ,
        ProductionUnit {
            public Object get(WpStyleSetupEOImpl obj) {
                return obj.getProductionUnit();
            }

            public void put(WpStyleSetupEOImpl obj, Object value) {
                obj.setProductionUnit((Number)value);
            }
        }
        ,
        LcUnit {
            public Object get(WpStyleSetupEOImpl obj) {
                return obj.getLcUnit();
            }

            public void put(WpStyleSetupEOImpl obj, Object value) {
                obj.setLcUnit((Number)value);
            }
        }
        ,
        Version {
            public Object get(WpStyleSetupEOImpl obj) {
                return obj.getVersion();
            }

            public void put(WpStyleSetupEOImpl obj, Object value) {
                obj.setVersion((Number)value);
            }
        }
        ,
        PbFlag {
            public Object get(WpStyleSetupEOImpl obj) {
                return obj.getPbFlag();
            }

            public void put(WpStyleSetupEOImpl obj, Object value) {
                obj.setPbFlag((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(WpStyleSetupEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(WpStyleSetupEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(WpStyleSetupEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(WpStyleSetupEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(WpStyleSetupEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(WpStyleSetupEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(WpStyleSetupEOImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(WpStyleSetupEOImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        WpStyleWiseProcessSamEO {
            public Object get(WpStyleSetupEOImpl obj) {
                return obj.getWpStyleWiseProcessSamEO();
            }

            public void put(WpStyleSetupEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(WpStyleSetupEOImpl object);

        public abstract void put(WpStyleSetupEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int STYLESETUPID = AttributesEnum.StyleSetupId.index();
    public static final int SYSTEMID = AttributesEnum.SystemId.index();
    public static final int ORDERQTY = AttributesEnum.OrderQty.index();
    public static final int PRODUCTIONUNIT = AttributesEnum.ProductionUnit.index();
    public static final int LCUNIT = AttributesEnum.LcUnit.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int PBFLAG = AttributesEnum.PbFlag.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int WPSTYLEWISEPROCESSSAMEO = AttributesEnum.WpStyleWiseProcessSamEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public WpStyleSetupEOImpl() {
    }

    /**
     * Gets the attribute value for StyleSetupId, using the alias name StyleSetupId.
     * @return the StyleSetupId
     */
    public Number getStyleSetupId() {
        return (Number)getAttributeInternal(STYLESETUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for StyleSetupId.
     * @param value value to set the StyleSetupId
     */
    public void setStyleSetupId(Number value) {
        setAttributeInternal(STYLESETUPID, value);
    }

    /**
     * Gets the attribute value for SystemId, using the alias name SystemId.
     * @return the SystemId
     */
    public Number getSystemId() {
        return (Number)getAttributeInternal(SYSTEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SystemId.
     * @param value value to set the SystemId
     */
    public void setSystemId(Number value) {
        setAttributeInternal(SYSTEMID, value);
    }

    /**
     * Gets the attribute value for OrderQty, using the alias name OrderQty.
     * @return the OrderQty
     */
    public Number getOrderQty() {
        return (Number)getAttributeInternal(ORDERQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderQty.
     * @param value value to set the OrderQty
     */
    public void setOrderQty(Number value) {
        setAttributeInternal(ORDERQTY, value);
    }

    /**
     * Gets the attribute value for ProductionUnit, using the alias name ProductionUnit.
     * @return the ProductionUnit
     */
    public Number getProductionUnit() {
        return (Number)getAttributeInternal(PRODUCTIONUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductionUnit.
     * @param value value to set the ProductionUnit
     */
    public void setProductionUnit(Number value) {
        setAttributeInternal(PRODUCTIONUNIT, value);
    }

    /**
     * Gets the attribute value for LcUnit, using the alias name LcUnit.
     * @return the LcUnit
     */
    public Number getLcUnit() {
        return (Number)getAttributeInternal(LCUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for LcUnit.
     * @param value value to set the LcUnit
     */
    public void setLcUnit(Number value) {
        setAttributeInternal(LCUNIT, value);
    }

    /**
     * Gets the attribute value for Version, using the alias name Version.
     * @return the Version
     */
    public Number getVersion() {
        return (Number)getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Version.
     * @param value value to set the Version
     */
    public void setVersion(Number value) {
        setAttributeInternal(VERSION, value);
    }

    /**
     * Gets the attribute value for PbFlag, using the alias name PbFlag.
     * @return the PbFlag
     */
    public String getPbFlag() {
        return (String)getAttributeInternal(PBFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for PbFlag.
     * @param value value to set the PbFlag
     */
    public void setPbFlag(String value) {
        setAttributeInternal(PBFLAG, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getWpStyleWiseProcessSamEO() {
        return (RowIterator)getAttributeInternal(WPSTYLEWISEPROCESSSAMEO);
    }

    /**
     * @param styleSetupId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number styleSetupId) {
        return new Key(new Object[]{styleSetupId});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model.entity.WpStyleSetupEO");
        }
        return mDefinitionObject;
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
     protected void create(AttributeList attributeList) {
         
         Map sessionScope = ADFContext.getCurrent().getSessionScope();
        String orgId = (String)sessionScope.get("orgId");
         
            super.create(attributeList);
  
             oracle.jbo.server.SequenceImpl s =
             new oracle.jbo.server.SequenceImpl("WP_STYLE_SETUP_SEQ",  getDBTransaction());
            oracle.jbo.domain.Number sVal = s.getSequenceNumber();
             this.setStyleSetupId(sVal);
               
          

     }

     /**
      * Add locking logic here.
      */
     public void lock() {
         super.lock();
     }

     /**
      * Custom DML update/insert/delete logic here.
      * @param operation the operation type
      * @param e the transaction event
      */
     protected void doDML(int operation, TransactionEvent e) {
         Map sessionScope = ADFContext.getCurrent().getSessionScope();
              String user = (String)sessionScope.get("userId");
              
         //        System.out.println("Document No -->" + getSrNoString());
               
              if (DML_UPDATE == operation) {
                  try {
                      setLastUpdatedDate((Date)Date.getCurrentDate());
                      setLastUpdatedBy(new oracle.jbo.domain.Number(user));              
                      
                  } catch (SQLException f) {
                      f.printStackTrace();
                  }
              } else if (DML_INSERT == operation) {

                  try {
                    
                      setCreationDate((Date)Date.getCurrentDate());
                      setCreatedBy(new oracle.jbo.domain.Number(user));

                  } catch (SQLException f) {
                      f.printStackTrace();
                  }
              }
              
          
         super.doDML(operation, e);
     }
}
