package model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 29 12:15:38 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CWPLDefaultProcessesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CWPLDefaultProcessesVOImpl() {
    }
}
