package model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 29 12:01:45 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PopulateProcessVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PopulateProcessVOImpl() {
    }
}
