package model.view;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 29 12:01:45 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PopulateProcessVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        OrgId {
            public Object get(PopulateProcessVORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(PopulateProcessVORowImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        WpSectionId {
            public Object get(PopulateProcessVORowImpl obj) {
                return obj.getWpSectionId();
            }

            public void put(PopulateProcessVORowImpl obj, Object value) {
                obj.setWpSectionId((Number)value);
            }
        }
        ,
        UnitSectionId {
            public Object get(PopulateProcessVORowImpl obj) {
                return obj.getUnitSectionId();
            }

            public void put(PopulateProcessVORowImpl obj, Object value) {
                obj.setUnitSectionId((Number)value);
            }
        }
        ,
        SectionName {
            public Object get(PopulateProcessVORowImpl obj) {
                return obj.getSectionName();
            }

            public void put(PopulateProcessVORowImpl obj, Object value) {
                obj.setSectionName((String)value);
            }
        }
        ,
        Serial {
            public Object get(PopulateProcessVORowImpl obj) {
                return obj.getSerial();
            }

            public void put(PopulateProcessVORowImpl obj, Object value) {
                obj.setSerial((Number)value);
            }
        }
        ,
        WpProcessId {
            public Object get(PopulateProcessVORowImpl obj) {
                return obj.getWpProcessId();
            }

            public void put(PopulateProcessVORowImpl obj, Object value) {
                obj.setWpProcessId((Number)value);
            }
        }
        ,
        UnitProcessId {
            public Object get(PopulateProcessVORowImpl obj) {
                return obj.getUnitProcessId();
            }

            public void put(PopulateProcessVORowImpl obj, Object value) {
                obj.setUnitProcessId((Number)value);
            }
        }
        ,
        ProcessName {
            public Object get(PopulateProcessVORowImpl obj) {
                return obj.getProcessName();
            }

            public void put(PopulateProcessVORowImpl obj, Object value) {
                obj.setProcessName((String)value);
            }
        }
        ,
        SectionType {
            public Object get(PopulateProcessVORowImpl obj) {
                return obj.getSectionType();
            }

            public void put(PopulateProcessVORowImpl obj, Object value) {
                obj.setSectionType((String)value);
            }
        }
        ,
        SelectProcess {
            public Object get(PopulateProcessVORowImpl obj) {
                return obj.getSelectProcess();
            }

            public void put(PopulateProcessVORowImpl obj, Object value) {
                obj.setSelectProcess((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(PopulateProcessVORowImpl object);

        public abstract void put(PopulateProcessVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int WPSECTIONID = AttributesEnum.WpSectionId.index();
    public static final int UNITSECTIONID = AttributesEnum.UnitSectionId.index();
    public static final int SECTIONNAME = AttributesEnum.SectionName.index();
    public static final int SERIAL = AttributesEnum.Serial.index();
    public static final int WPPROCESSID = AttributesEnum.WpProcessId.index();
    public static final int UNITPROCESSID = AttributesEnum.UnitProcessId.index();
    public static final int PROCESSNAME = AttributesEnum.ProcessName.index();
    public static final int SECTIONTYPE = AttributesEnum.SectionType.index();
    public static final int SELECTPROCESS = AttributesEnum.SelectProcess.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PopulateProcessVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrgId.
     * @param value value to set the  OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WpSectionId.
     * @return the WpSectionId
     */
    public Number getWpSectionId() {
        return (Number) getAttributeInternal(WPSECTIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WpSectionId.
     * @param value value to set the  WpSectionId
     */
    public void setWpSectionId(Number value) {
        setAttributeInternal(WPSECTIONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UnitSectionId.
     * @return the UnitSectionId
     */
    public Number getUnitSectionId() {
        return (Number) getAttributeInternal(UNITSECTIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UnitSectionId.
     * @param value value to set the  UnitSectionId
     */
    public void setUnitSectionId(Number value) {
        setAttributeInternal(UNITSECTIONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SectionName.
     * @return the SectionName
     */
    public String getSectionName() {
        return (String) getAttributeInternal(SECTIONNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SectionName.
     * @param value value to set the  SectionName
     */
    public void setSectionName(String value) {
        setAttributeInternal(SECTIONNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Serial.
     * @return the Serial
     */
    public Number getSerial() {
        return (Number) getAttributeInternal(SERIAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Serial.
     * @param value value to set the  Serial
     */
    public void setSerial(Number value) {
        setAttributeInternal(SERIAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WpProcessId.
     * @return the WpProcessId
     */
    public Number getWpProcessId() {
        return (Number) getAttributeInternal(WPPROCESSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WpProcessId.
     * @param value value to set the  WpProcessId
     */
    public void setWpProcessId(Number value) {
        setAttributeInternal(WPPROCESSID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UnitProcessId.
     * @return the UnitProcessId
     */
    public Number getUnitProcessId() {
        return (Number) getAttributeInternal(UNITPROCESSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UnitProcessId.
     * @param value value to set the  UnitProcessId
     */
    public void setUnitProcessId(Number value) {
        setAttributeInternal(UNITPROCESSID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProcessName.
     * @return the ProcessName
     */
    public String getProcessName() {
        return (String) getAttributeInternal(PROCESSNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProcessName.
     * @param value value to set the  ProcessName
     */
    public void setProcessName(String value) {
        setAttributeInternal(PROCESSNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SectionType.
     * @return the SectionType
     */
    public String getSectionType() {
        return (String) getAttributeInternal(SECTIONTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SectionType.
     * @param value value to set the  SectionType
     */
    public void setSectionType(String value) {
        setAttributeInternal(SECTIONTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SelectProcess.
     * @return the SelectProcess
     */
    public String getSelectProcess() {
        return (String) getAttributeInternal(SELECTPROCESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SelectProcess.
     * @param value value to set the  SelectProcess
     */
    public void setSelectProcess(String value) {
        setAttributeInternal(SELECTPROCESS, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
