package model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 05 08:54:44 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SamVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SamVOImpl() {
    }

    /**
     * Returns the bind variable value for p_system_id.
     * @return bind variable value for p_system_id
     */
    public String getp_system_id() {
        return (String)getNamedWhereClauseParam("p_system_id");
    }

    /**
     * Sets <code>value</code> for bind variable p_system_id.
     * @param value value to bind as p_system_id
     */
    public void setp_system_id(String value) {
        setNamedWhereClauseParam("p_system_id", value);
    }
}
