package model.view;

import model.entity.WpStyleSetupEOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 04 22:06:54 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WpStyleSetupVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        StyleSetupId {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getStyleSetupId();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setStyleSetupId((Number)value);
            }
        }
        ,
        SystemId {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getSystemId();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setSystemId((Number)value);
            }
        }
        ,
        LcUnit {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getLcUnit();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setLcUnit((Number)value);
            }
        }
        ,
        LcUnitName {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getLcUnitName();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setLcUnitName((String)value);
            }
        }
        ,
        BuyerId {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getBuyerId();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        BuyerName {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getBuyerName();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setBuyerName((String)value);
            }
        }
        ,
        Season {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getSeason();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        Style {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getStyle();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setStyle((String)value);
            }
        }
        ,
        Color {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getColor();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setColor((String)value);
            }
        }
        ,
        WashName {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getWashName();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setWashName((String)value);
            }
        }
        ,
        OrderQty {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getOrderQty();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setOrderQty((Number)value);
            }
        }
        ,
        ProductionUnit {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getProductionUnit();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setProductionUnit((Number)value);
            }
        }
        ,
        ProductionUnitName {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getProductionUnitName();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setProductionUnitName((String)value);
            }
        }
        ,
        PbFlag {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getPbFlag();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setPbFlag((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        SamVersion {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getSamVersion();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setSamVersion((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        ProjectionStyle {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getProjectionStyle();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setProjectionStyle((String)value);
            }
        }
        ,
        AvailableSamVersion {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getAvailableSamVersion();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setAvailableSamVersion((Number)value);
            }
        }
        ,
        UpdatedVersionAvailavle {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getUpdatedVersionAvailavle();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setUpdatedVersionAvailavle((Boolean)value);
            }
        }
        ,
        WpStyleWiseProcessSamVO {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getWpStyleWiseProcessSamVO();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        OrgLOV1 {
            public Object get(WpStyleSetupVORowImpl obj) {
                return obj.getOrgLOV1();
            }

            public void put(WpStyleSetupVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(WpStyleSetupVORowImpl object);

        public abstract void put(WpStyleSetupVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int STYLESETUPID = AttributesEnum.StyleSetupId.index();
    public static final int SYSTEMID = AttributesEnum.SystemId.index();
    public static final int LCUNIT = AttributesEnum.LcUnit.index();
    public static final int LCUNITNAME = AttributesEnum.LcUnitName.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int BUYERNAME = AttributesEnum.BuyerName.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int STYLE = AttributesEnum.Style.index();
    public static final int COLOR = AttributesEnum.Color.index();
    public static final int WASHNAME = AttributesEnum.WashName.index();
    public static final int ORDERQTY = AttributesEnum.OrderQty.index();
    public static final int PRODUCTIONUNIT = AttributesEnum.ProductionUnit.index();
    public static final int PRODUCTIONUNITNAME = AttributesEnum.ProductionUnitName.index();
    public static final int PBFLAG = AttributesEnum.PbFlag.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int SAMVERSION = AttributesEnum.SamVersion.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int PROJECTIONSTYLE = AttributesEnum.ProjectionStyle.index();
    public static final int AVAILABLESAMVERSION = AttributesEnum.AvailableSamVersion.index();
    public static final int UPDATEDVERSIONAVAILAVLE = AttributesEnum.UpdatedVersionAvailavle.index();
    public static final int WPSTYLEWISEPROCESSSAMVO = AttributesEnum.WpStyleWiseProcessSamVO.index();
    public static final int ORGLOV1 = AttributesEnum.OrgLOV1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public WpStyleSetupVORowImpl() {
    }

    /**
     * Gets WpStyleSetupEO entity object.
     * @return the WpStyleSetupEO
     */
    public WpStyleSetupEOImpl getWpStyleSetupEO() {
        return (WpStyleSetupEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for STYLE_SETUP_ID using the alias name StyleSetupId.
     * @return the STYLE_SETUP_ID
     */
    public Number getStyleSetupId() {
        return (Number) getAttributeInternal(STYLESETUPID);
    }

    /**
     * Sets <code>value</code> as attribute value for STYLE_SETUP_ID using the alias name StyleSetupId.
     * @param value value to set the STYLE_SETUP_ID
     */
    public void setStyleSetupId(Number value) {
        setAttributeInternal(STYLESETUPID, value);
    }

    /**
     * Gets the attribute value for SYSTEM_ID using the alias name SystemId.
     * @return the SYSTEM_ID
     */
    public Number getSystemId() {
        return (Number) getAttributeInternal(SYSTEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for SYSTEM_ID using the alias name SystemId.
     * @param value value to set the SYSTEM_ID
     */
    public void setSystemId(Number value) {
        setAttributeInternal(SYSTEMID, value);
    }


    /**
     * Gets the attribute value for the calculated attribute LcUnit.
     * @return the LcUnit
     */
    public Number getLcUnit() {
        return (Number) getAttributeInternal(LCUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LcUnit.
     * @param value value to set the  LcUnit
     */
    public void setLcUnit(Number value) {
        setAttributeInternal(LCUNIT, value);
    }

    /**
     * Gets the attribute value for PRODUCTION_UNIT using the alias name ProductionUnit.
     * @return the PRODUCTION_UNIT
     */
    public Number getProductionUnit() {
        return (Number) getAttributeInternal(PRODUCTIONUNIT);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCTION_UNIT using the alias name ProductionUnit.
     * @param value value to set the PRODUCTION_UNIT
     */
    public void setProductionUnit(Number value) {
        setAttributeInternal(PRODUCTIONUNIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductionUnitName.
     * @return the ProductionUnitName
     */
    public String getProductionUnitName() {
        return (String) getAttributeInternal(PRODUCTIONUNITNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductionUnitName.
     * @param value value to set the  ProductionUnitName
     */
    public void setProductionUnitName(String value) {
        setAttributeInternal(PRODUCTIONUNITNAME, value);
    }


    /**
     * Gets the attribute value for the calculated attribute LcUnitName.
     * @return the LcUnitName
     */
    public String getLcUnitName() {
        return (String) getAttributeInternal(LCUNITNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LcUnitName.
     * @param value value to set the  LcUnitName
     */
    public void setLcUnitName(String value) {
        setAttributeInternal(LCUNITNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuyerId.
     * @return the BuyerId
     */
    public Number getBuyerId() {
        return (Number) getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuyerId.
     * @param value value to set the  BuyerId
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuyerName.
     * @return the BuyerName
     */
    public String getBuyerName() {
        return (String) getAttributeInternal(BUYERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuyerName.
     * @param value value to set the  BuyerName
     */
    public void setBuyerName(String value) {
        setAttributeInternal(BUYERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Season.
     * @return the Season
     */
    public String getSeason() {
        return (String) getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Season.
     * @param value value to set the  Season
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Style.
     * @return the Style
     */
    public String getStyle() {
        return (String) getAttributeInternal(STYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Style.
     * @param value value to set the  Style
     */
    public void setStyle(String value) {
        setAttributeInternal(STYLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Color.
     * @return the Color
     */
    public String getColor() {
        return (String) getAttributeInternal(COLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Color.
     * @param value value to set the  Color
     */
    public void setColor(String value) {
        setAttributeInternal(COLOR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WashName.
     * @return the WashName
     */
    public String getWashName() {
        return (String) getAttributeInternal(WASHNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WashName.
     * @param value value to set the  WashName
     */
    public void setWashName(String value) {
        setAttributeInternal(WASHNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrderQty.
     * @return the OrderQty
     */
    public Number getOrderQty() {
        return (Number) getAttributeInternal(ORDERQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrderQty.
     * @param value value to set the  OrderQty
     */
    public void setOrderQty(Number value) {
        setAttributeInternal(ORDERQTY, value);
    }

    /**
     * Gets the attribute value for PB_FLAG using the alias name PbFlag.
     * @return the PB_FLAG
     */
    public String getPbFlag() {
        return (String) getAttributeInternal(PBFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for PB_FLAG using the alias name PbFlag.
     * @param value value to set the PB_FLAG
     */
    public void setPbFlag(String value) {
        setAttributeInternal(PBFLAG, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate() {
        return (Date) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for SAM_VERSION using the alias name SamVersion.
     * @return the SAM_VERSION
     */
    public Number getSamVersion() {
        return (Number) getAttributeInternal(SAMVERSION);
    }

    /**
     * Sets <code>value</code> as attribute value for SAM_VERSION using the alias name SamVersion.
     * @param value value to set the SAM_VERSION
     */
    public void setSamVersion(Number value) {
        setAttributeInternal(SAMVERSION, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AvailableSamVersion.
     * @return the AvailableSamVersion
     */
    public Number getAvailableSamVersion() {
        return (Number) getAttributeInternal(AVAILABLESAMVERSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AvailableSamVersion.
     * @param value value to set the  AvailableSamVersion
     */
    public void setAvailableSamVersion(Number value) {
        setAttributeInternal(AVAILABLESAMVERSION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UpdatedVersionAvailavle.
     * @return the UpdatedVersionAvailavle
     */
    public Boolean getUpdatedVersionAvailavle() {
        return (Boolean) getAttributeInternal(UPDATEDVERSIONAVAILAVLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UpdatedVersionAvailavle.
     * @param value value to set the  UpdatedVersionAvailavle
     */
    public void setUpdatedVersionAvailavle(Boolean value) {
        setAttributeInternal(UPDATEDVERSIONAVAILAVLE, value);
    }

    /**
     * Gets the attribute value for PROJECTION_STYLE using the alias name ProjectionStyle.
     * @return the PROJECTION_STYLE
     */
    public String getProjectionStyle() {
        return (String) getAttributeInternal(PROJECTIONSTYLE);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECTION_STYLE using the alias name ProjectionStyle.
     * @param value value to set the PROJECTION_STYLE
     */
    public void setProjectionStyle(String value) {
        setAttributeInternal(PROJECTIONSTYLE, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link WpStyleWiseProcessSamVO.
     */
    public RowIterator getWpStyleWiseProcessSamVO() {
        return (RowIterator)getAttributeInternal(WPSTYLEWISEPROCESSSAMVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OrgLOV1.
     */
    public RowSet getOrgLOV1() {
        return (RowSet)getAttributeInternal(ORGLOV1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
