package model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 05 09:00:16 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WpStyleWiseProcessSamVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public WpStyleWiseProcessSamVOImpl() {
    }
}
