package model.view;

import model.entity.WpStyleWiseProcessSamEOImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 05 09:00:16 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WpStyleWiseProcessSamVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        SamId {
            public Object get(WpStyleWiseProcessSamVORowImpl obj) {
                return obj.getSamId();
            }

            public void put(WpStyleWiseProcessSamVORowImpl obj, Object value) {
                obj.setSamId((Number)value);
            }
        }
        ,
        StyleSetupId {
            public Object get(WpStyleWiseProcessSamVORowImpl obj) {
                return obj.getStyleSetupId();
            }

            public void put(WpStyleWiseProcessSamVORowImpl obj, Object value) {
                obj.setStyleSetupId((Number)value);
            }
        }
        ,
        WpProcessId {
            public Object get(WpStyleWiseProcessSamVORowImpl obj) {
                return obj.getWpProcessId();
            }

            public void put(WpStyleWiseProcessSamVORowImpl obj, Object value) {
                obj.setWpProcessId((Number)value);
            }
        }
        ,
        ProcessSeq {
            public Object get(WpStyleWiseProcessSamVORowImpl obj) {
                return obj.getProcessSeq();
            }

            public void put(WpStyleWiseProcessSamVORowImpl obj, Object value) {
                obj.setProcessSeq((Number)value);
            }
        }
        ,
        PlanDay {
            public Object get(WpStyleWiseProcessSamVORowImpl obj) {
                return obj.getPlanDay();
            }

            public void put(WpStyleWiseProcessSamVORowImpl obj, Object value) {
                obj.setPlanDay((Number)value);
            }
        }
        ,
        BatchQty {
            public Object get(WpStyleWiseProcessSamVORowImpl obj) {
                return obj.getBatchQty();
            }

            public void put(WpStyleWiseProcessSamVORowImpl obj, Object value) {
                obj.setBatchQty((Number)value);
            }
        }
        ,
        BatchTime {
            public Object get(WpStyleWiseProcessSamVORowImpl obj) {
                return obj.getBatchTime();
            }

            public void put(WpStyleWiseProcessSamVORowImpl obj, Object value) {
                obj.setBatchTime((Number)value);
            }
        }
        ,
        Sam {
            public Object get(WpStyleWiseProcessSamVORowImpl obj) {
                return obj.getSam();
            }

            public void put(WpStyleWiseProcessSamVORowImpl obj, Object value) {
                obj.setSam((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(WpStyleWiseProcessSamVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(WpStyleWiseProcessSamVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(WpStyleWiseProcessSamVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(WpStyleWiseProcessSamVORowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(WpStyleWiseProcessSamVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(WpStyleWiseProcessSamVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(WpStyleWiseProcessSamVORowImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(WpStyleWiseProcessSamVORowImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        SamVersion {
            public Object get(WpStyleWiseProcessSamVORowImpl obj) {
                return obj.getSamVersion();
            }

            public void put(WpStyleWiseProcessSamVORowImpl obj, Object value) {
                obj.setSamVersion((Number)value);
            }
        }
        ,
        SystemId {
            public Object get(WpStyleWiseProcessSamVORowImpl obj) {
                return obj.getSystemId();
            }

            public void put(WpStyleWiseProcessSamVORowImpl obj, Object value) {
                obj.setSystemId((Number)value);
            }
        }
        ,
        ProcessName {
            public Object get(WpStyleWiseProcessSamVORowImpl obj) {
                return obj.getProcessName();
            }

            public void put(WpStyleWiseProcessSamVORowImpl obj, Object value) {
                obj.setProcessName((String)value);
            }
        }
        ,
        SectionType {
            public Object get(WpStyleWiseProcessSamVORowImpl obj) {
                return obj.getSectionType();
            }

            public void put(WpStyleWiseProcessSamVORowImpl obj, Object value) {
                obj.setSectionType((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(WpStyleWiseProcessSamVORowImpl object);

        public abstract void put(WpStyleWiseProcessSamVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SAMID = AttributesEnum.SamId.index();
    public static final int STYLESETUPID = AttributesEnum.StyleSetupId.index();
    public static final int WPPROCESSID = AttributesEnum.WpProcessId.index();
    public static final int PROCESSSEQ = AttributesEnum.ProcessSeq.index();
    public static final int PLANDAY = AttributesEnum.PlanDay.index();
    public static final int BATCHQTY = AttributesEnum.BatchQty.index();
    public static final int BATCHTIME = AttributesEnum.BatchTime.index();
    public static final int SAM = AttributesEnum.Sam.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int SAMVERSION = AttributesEnum.SamVersion.index();
    public static final int SYSTEMID = AttributesEnum.SystemId.index();
    public static final int PROCESSNAME = AttributesEnum.ProcessName.index();
    public static final int SECTIONTYPE = AttributesEnum.SectionType.index();

    /**
     * This is the default constructor (do not remove).
     */
    public WpStyleWiseProcessSamVORowImpl() {
    }

    /**
     * Gets WpStyleWiseProcessSamEO entity object.
     * @return the WpStyleWiseProcessSamEO
     */
    public WpStyleWiseProcessSamEOImpl getWpStyleWiseProcessSamEO() {
        return (WpStyleWiseProcessSamEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for SAM_ID using the alias name SamId.
     * @return the SAM_ID
     */
    public Number getSamId() {
        return (Number) getAttributeInternal(SAMID);
    }

    /**
     * Sets <code>value</code> as attribute value for SAM_ID using the alias name SamId.
     * @param value value to set the SAM_ID
     */
    public void setSamId(Number value) {
        setAttributeInternal(SAMID, value);
    }

    /**
     * Gets the attribute value for STYLE_SETUP_ID using the alias name StyleSetupId.
     * @return the STYLE_SETUP_ID
     */
    public Number getStyleSetupId() {
        return (Number) getAttributeInternal(STYLESETUPID);
    }

    /**
     * Sets <code>value</code> as attribute value for STYLE_SETUP_ID using the alias name StyleSetupId.
     * @param value value to set the STYLE_SETUP_ID
     */
    public void setStyleSetupId(Number value) {
        setAttributeInternal(STYLESETUPID, value);
    }

    /**
     * Gets the attribute value for WP_PROCESS_ID using the alias name WpProcessId.
     * @return the WP_PROCESS_ID
     */
    public Number getWpProcessId() {
        return (Number) getAttributeInternal(WPPROCESSID);
    }

    /**
     * Sets <code>value</code> as attribute value for WP_PROCESS_ID using the alias name WpProcessId.
     * @param value value to set the WP_PROCESS_ID
     */
    public void setWpProcessId(Number value) {
        setAttributeInternal(WPPROCESSID, value);
    }

    /**
     * Gets the attribute value for PROCESS_SEQ using the alias name ProcessSeq.
     * @return the PROCESS_SEQ
     */
    public Number getProcessSeq() {
        return (Number) getAttributeInternal(PROCESSSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for PROCESS_SEQ using the alias name ProcessSeq.
     * @param value value to set the PROCESS_SEQ
     */
    public void setProcessSeq(Number value) {
        setAttributeInternal(PROCESSSEQ, value);
    }

    /**
     * Gets the attribute value for PLAN_DAY using the alias name PlanDay.
     * @return the PLAN_DAY
     */
    public Number getPlanDay() {
        return (Number) getAttributeInternal(PLANDAY);
    }

    /**
     * Sets <code>value</code> as attribute value for PLAN_DAY using the alias name PlanDay.
     * @param value value to set the PLAN_DAY
     */
    public void setPlanDay(Number value) {
        setAttributeInternal(PLANDAY, value);
    }

    /**
     * Gets the attribute value for BATCH_QTY using the alias name BatchQty.
     * @return the BATCH_QTY
     */
    public Number getBatchQty() {
        return (Number) getAttributeInternal(BATCHQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for BATCH_QTY using the alias name BatchQty.
     * @param value value to set the BATCH_QTY
     */
    public void setBatchQty(Number value) {
        setAttributeInternal(BATCHQTY, value);
    }

    /**
     * Gets the attribute value for BATCH_TIME using the alias name BatchTime.
     * @return the BATCH_TIME
     */
    public Number getBatchTime() {
        return (Number) getAttributeInternal(BATCHTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for BATCH_TIME using the alias name BatchTime.
     * @param value value to set the BATCH_TIME
     */
    public void setBatchTime(Number value) {
        setAttributeInternal(BATCHTIME, value);
    }

    /**
     * Gets the attribute value for SAM using the alias name Sam.
     * @return the SAM
     */
    public Number getSam() {
        return (Number) getAttributeInternal(SAM);
    }

    /**
     * Sets <code>value</code> as attribute value for SAM using the alias name Sam.
     * @param value value to set the SAM
     */
    public void setSam(Number value) {
        setAttributeInternal(SAM, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate() {
        return (Date) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProcessName.
     * @return the ProcessName
     */
    public String getProcessName() {
        return (String) getAttributeInternal(PROCESSNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProcessName.
     * @param value value to set the  ProcessName
     */
    public void setProcessName(String value) {
        setAttributeInternal(PROCESSNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SectionType.
     * @return the SectionType
     */
    public String getSectionType() {
        return (String) getAttributeInternal(SECTIONTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SectionType.
     * @param value value to set the  SectionType
     */
    public void setSectionType(String value) {
        setAttributeInternal(SECTIONTYPE, value);
    }

    /**
     * Gets the attribute value for SYSTEM_ID using the alias name SystemId.
     * @return the SYSTEM_ID
     */
    public Number getSystemId() {
        return (Number) getAttributeInternal(SYSTEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for SYSTEM_ID using the alias name SystemId.
     * @param value value to set the SYSTEM_ID
     */
    public void setSystemId(Number value) {
        setAttributeInternal(SYSTEMID, value);
    }

    /**
     * Gets the attribute value for SAM_VERSION using the alias name SamVersion.
     * @return the SAM_VERSION
     */
    public Number getSamVersion() {
        return (Number) getAttributeInternal(SAMVERSION);
    }

    /**
     * Sets <code>value</code> as attribute value for SAM_VERSION using the alias name SamVersion.
     * @param value value to set the SAM_VERSION
     */
    public void setSamVersion(Number value) {
        setAttributeInternal(SAMVERSION, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
